name: pull_request
on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    inputs:
      database_url:
        description: "Database URL for tests"
        required: true
      nextauth_secret:
        description: "NextAuth secret for tests"
        required: true
      nextauth_url:
        description: "NextAuth URL for tests"
        required: true
      discord_client_id:
        description: "Discord Client ID for tests"
        required: true
      discord_client_secret:
        description: "Discord Client Secret for tests"
        required: true
      auth_github_id:
        description: "GitHub ID for tests"
        required: true
      auth_github_secret:
        description: "GitHub Secret for tests"
        required: true
    env:
      DATABASE_URL: ${{ github.event.inputs.DATABASE_URL}}
      NEXTAUTH_SECRET: ${{ github.event.inputs.NEXTAUTH_SECRET}}
      NEXTAUTH_URL: ${{ github.event.inputs.NEXTAUTH_URL}}
      DISCORD_CLIENT_ID: ${{ github.event.inputs.DISCORD_CLIENT_ID}}
      DISCORD_CLIENT_SECRET: ${{ github.event.inputs.DISCORD_CLIENT_SECRET}}
      AUTH_GITHUB_ID: ${{ github.event.inputs.AUTH_GITHUB_ID}}
      AUTH_GITHUB_SECRET: ${{ github.event.inputs.AUTH_GITHUB_SECRET}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.14.1"

      - name: Print environment variables
        run: |
          echo "Database URL: ${{ inputs.database_url }}"
          echo "NextAuth Secret: ${{ inputs.nextauth_secret }}"
          # 打印其他 inputs 变量...

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test # 使用输入参数代替 Secrets，例如：$DATABASE_URL 改为 ${{ inputs.database_url }}
