name: pull_request
on:
  pull_request:
    branches:
      - master # 这里指定你希望测试的分支，例如 master
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: mysql://root:123456@127.0.0.1:3306/mydatabase
      NEXTAUTH_SECRET: lXysSFqiiRbsq98ZIkrP6Rquse
      NEXTAUTH_URL: localhost:3000
      DISCORD_CLIENT_ID: 765033707565058
      DISCORD_CLIENT_SECRET: c0kj1k0frws72z3mq8nc
      AUTH_GITHUB_ID: w4s059crr8baf6ghk28b
      AUTH_GITHUB_SECRET: z5wel3ol5cxqvxkiv43kb4x3gs4gydxz
      # 方便PR测试，仅为mock数据
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.1 # 这里指定你希望使用的 Node.js 版本
      - name: cache clean
        run: yarn cache clean
      - name: Print environment variables
        run: |
          echo $DATABASE_URL
          echo $NEXTAUTH_SECRET
          # 打印其他 secrets 变量...
      - name: Install dependencies
        run: yarn # 这里可以根据你的项目使用适当的包管理器进行安装

      - name: Run tests
        run: yarn test:ci # 这里运行你的测试脚本或命令
